language: node_js

services:
  - docker
  - postgres

before_script:
  - psql -c 'create database hsl_test;' -U postgres

before_install:
- docker build -t members_api:latest .
- >-
  docker run
  -e NODE_PORT=3000
  -e NODE_ENV=development
  -e SENDGRID_API_KEY="some big ass sendgrid key"
  -e DATABASE_URL="postgres://postgres@`hostname`:5432/hsl_test"
  -e JWT_KEY="some random key"
  --net host
  members_api:latest /bin/sh -c "npm install && npm run test"

script:
- npm run test