language: node_js

services:
  - docker

before_script:
  - cp docker-compose.dist.yml docker-compose.yml && sed -i "s^/home/YOUR_USER/YOUR_PATH/THIS_FOLDER^`pwd`^g" docker-compose.yml
  - docker-compose up

script:
  - docker exec -it members_api /bin/sh -c 'npm run up && npm run test'