version: "3"
services:
  api:
    container_name: members_api
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      NODE_PORT: 3000
      NODE_ENV: "development"
      SENDGRID_API_KEY: "some big ass sendgrid key"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/hsl_dev"
      JWT_KEY: "some random key"
    volumes:
      - /home/YOUR_USER/YOUR_PATH/members_api:/home/app

  postgres:
    container_name: members_postgres
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hsl_dev

